### ISSUE TITLE
[Feat]: Rocket Config support

### ISSUE THREAD

**Issue by GeekMasher** [42ByteLabs/octoapp#1]
### What new feature are you looking for / expect?

Would be great if we can have the settings defined in the `Rocket.toml` file.

```toml
[github.app]
app_name = "My App"
# ...
```

### Expectations

Nice to have
